sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t rahulinux/boto3 .
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push rahulinux/boto3
